Added dynamic output library name depending on the platform

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -593,6 +593,7 @@ LDFLAGS
 CFLAGS
 CC
 gcc
+libfilename
 javaos
 javahome
 target_alias
@@ -1820,6 +1821,28 @@ for each in `ls ${javahome}/include` ;do
   fi;
 done;
 echo "JAVAOS=${javaos}"
+
+case $javaos in
+"linux")
+  libfilename="libjcurses.so"
+  ;;
+"darwin")
+  libfilename="libjcurses.dylib"
+  ;;
+
+"win32")
+  libfilename="jcurses.dll"
+  ;;
+
+*)
+  echo "Unrecognized platform. Aborting"
+  exit 1
+  ;;
+esac
+
+echo "LIBFILENAME=$libfilename"
+
+
 
 # Extract the first word of "gcc", so it can be a program name with args.
 set dummy gcc; ac_word=$2
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -8,7 +8,29 @@ for each in `ls ${javahome}/include` ;do
   fi;
 done;
 echo "JAVAOS=${javaos}"
+
+case $javaos in
+"linux")
+  libfilename="libjcurses.so"
+  ;;
+"darwin")
+  libfilename="libjcurses.dylib"
+  ;;
+
+"win32")
+  libfilename="jcurses.dll"
+  ;;
+
+*)
+  echo "Unrecognized platform. Aborting"
+  exit 1
+  ;;
+esac
+
+echo "LIBFILENAME=$libfilename"
+
 AC_SUBST(javaos)
+AC_SUBST(libfilename)
 AC_CHECK_PROG(gcc,gcc,gcc)
 AC_PROG_CC
 AC_CHECK_LIB(curses,initscr,curses=-lcurses)
